[DRAFT] Water victory
MrSamuelStreamer/WaterFlavourPack pull request #10
Opened 2024-09-23 18:08 UTC by keyz182

#7 

Still a work in progress, don't merge.

Looked to be easier to reimplement that to try to patch the archo quest. 

ToDo:
1) double check the storyteller patch to make sure we're making this quest auto-triggering
2) Validate it works - placing a Power Regulator should prompt the first quest. 
3) Descriptions and text - all still archonexus. Maybe for moving maps something like "As the machine roars into action, the ground seems to become unstable. You only have a few moments to grab your things and go". 
4) Set up "the victory". 
5) probably more.

2024-09-24 00:32 UTC, feldoh reviewed
honestly shrug, quests are basically unreviewable, part1 part3 signals that come from ? 🤷

2024-09-24 00:32 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_WaterVictory_Cycle.cs
> +      slate.Set("requiredWealth", 350000f);
presumably not relevant

2024-09-24 00:32 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_WaterVictory_Cycle.cs
> +      slate.Set("animalsAllowed", 5);
should probably be higher, we're not trying to restrict in the same way right he should be able to take more people.

2024-09-24 00:32 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_WaterVictory_Cycle.cs
> +        string newSignal1 = QuestGen.GenerateNewSignal("NewColonyCreated");
I know it's copy pasta but I'd dearly love the signals to have sensible names so it's more copiable and grokkable

2024-09-24 00:32 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_WaterVictory_Cycle.cs
> +      quest.AddPart(part3);
I simply can't parse this, I know it's copy paste but part one is an activatable quest part that is completed when built > 3; fine, but part three is a filter that checks the same condition for reasons? I assume it works but this is where I throw my hands up and say I don't understand the quest system

2024-09-24 00:32 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestPart_CatalyticSeparator.cs
> +        if(Find.TickManager.TicksGame % 60 != 0 || WaterVictoryWorldComponent.Instance.CatalyticSeparatorsBuilt < 3)
the targets shouldn't be repeatedly hard coded in so many places, grab them from settings or a static or something

2024-09-24 09:25 UTC, keyz182 commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_WaterVictory_Cycle.cs
> +      slate.Set("requiredWealth", 350000f);
Nope, will do a cleanup pass for all the gumph later today.

2024-09-24 09:26 UTC, keyz182 commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_WaterVictory_Cycle.cs
> +      quest.AddPart(part3);
Yeah, copypasta, so went with it. I'll have a play later to see if it's redundant or actually needed.

2024-10-06 22:21 UTC, feldoh requested changes
I think there's one or two actual errors I'm gonna push a quick re-prefix which you can review but don't have time to fix the rest today.

2024-10-06 22:21 UTC, feldoh commented on 1.5/Defs/BuildingDefs/MSS_Thirst_WaterQuest.xml
> +    <ThingDef Name="MSS_ArchoQuestBuilding" ParentName="BuildingBase" Abstract="True">
Missing _Thirst namespacing; I'm doing a full pass on that to bring it inline though there's a few that it's too late for

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/HarmonyPatches/Site_Patch.cs
> +    public static List<SitePartDef> SitesToNotDespawn = [
HashSet not list for membership

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/HarmonyPatches/StorytellerComp_RefiringUniqueQuest_Patch.cs
> +                        ? IntervalsPassed == (int) (Props.minDaysPassed * 60.0) + 1
same again, I think this should be >=
```suggestion
                        ? IntervalsPassed >= (int) (Props.minDaysPassed * 60.0) + 1
```

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/HarmonyPatches/StorytellerComp_RefiringUniqueQuest_Patch.cs
> +                    quest.cleanupTick >= 0 && IntervalsPassed == (int) (quest.cleanupTick + Props.refireEveryDays * 60000.0) / 1000)
```suggestion
                    quest.cleanupTick >= 0 && IntervalsPassed >= (int) (quest.cleanupTick + Props.refireEveryDays * 60000.0) / 1000)
```

Potential to get stuck I think. If that tick is skipped due to earlier filters intervals passed may be > your "nextFire". I think this should be `>=` instead of `==` but will leave it for you to review just in case I'm wrong and that gets it stuck in some other way.

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/HarmonyPatches/ThingStyleHelper_Patch.cs
> +            Find.World.GetComponent<ArchospringVictoryWorldComponent>().ArchoComponentsSeenByPlayer.Add(thing);
potential for duplication; swapping to hashset fixes this

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/Settings.cs
> +    public int WaterQuestRelicsAllowed = 10;
Pretty sure these are all irrelevant now there's no base move aspect.

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/ArchospringVictoryWorldComponent.cs
> +    public List<Thing> ArchoComponentsSeenByPlayer = [];
should be a hashset

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/Building_ArchoMachine.cs
> +        return (innerContainer.InnerListForReading.Count < 3 || innerContainer.InnerListForReading.Contains(t)) && GetStoreSettings().AllowedToAccept(t) && innerContainer.CanAcceptAnyOf(t);
as you've made the amount configurable in settings shouldn't this pull from there instead of hardcoding 3?

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/Building_ArchoMachine.cs
> +    public int SpaceRemainingFor(ThingDef _) => 3 - innerContainer.InnerListForReading.Count;
as you've made the amount configurable in settings shouldn't this pull from there instead of hardcoding 3?

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/Building_ArchoMachine.cs
> +    public void Notify_ItemRemoved(Thing_ComponentArcho item)
shouldn't this remove from the count you added to above?

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/Building_ArchoMachine.cs
> +        Find.World.GetComponent<ArchospringVictoryWorldComponent>().BuildingComponentCount.SetOrAdd(def, innerContainer.Count);
with this implementation you can never have more than one of these per def or they'll fight.

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/Building_ArchoMachine.cs
> +        sb.Append("MSS_Thirst_BuildingContainsComponents".Translate(innerContainer.Count));
perhaps $X/$Y ?

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/Building_ArchoMachine.cs
> +        if(innerContainer.Count < 3)
as you've made the amount configurable in settings shouldn't this pull from there instead of hardcoding 3?

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/MapGen/SitePartWorker_BarbCamp.cs
> +        ThingDef compDef = QuestGen.slate.Get<ThingDef>("archospringComponent");
I don't see this being added to a slate? Also it should be prefixed

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/MapGen/SitePartWorker_BarbCamp.cs
> +        component = component.MakeMinified();
idk why this wouldn't be just one line XD

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/MapGen/SymbolResolver_ArchoBuilding.cs
> +      }
you want to wrap the whole thing in a try finally to make sure that the `Thing.allowDestroyNonDestroyable = false;` definitely fires

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_ArchospringVictory_Cycle.cs
> +    public static string BuildingDestroyedGlobalSignal = "ArchoBuildingDestroyed";
Global so prefix?

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_ArchospringVictory_Cycle.cs
> +      string activated = QuestGen.GenerateNewSignal("ArchoBuildingComplete");
prefix

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_ArchospringVictory_Cycle.cs
> +      part1.archotechComponentSlateName = "archotechComponent";
shouldn't this be `archospringComponent`? or preferrably `mss_thirst_archospring_component` exxplains why I couldn't find the match earlier

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_ArchospringVictory_FirstCycle.cs
> +    protected override QuestPart_Activable_ArchoSpringBuilding Activable_ArchoSpringBuilding => new QuestPart_Activable_ArchoSpringBuilding(Thirst_Flavour_PackDefOf.MSS_PowerRegulator, 3);
its in the settings no?

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_ArchospringVictory_SecondCycle.cs
> +    protected override QuestPart_Activable_ArchoSpringBuilding Activable_ArchoSpringBuilding => new QuestPart_Activable_ArchoSpringBuilding(Thirst_Flavour_PackDefOf.MSS_CatalyticSeparator, 3);
is this not a setting?

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_ArchospringVictory_ThirdCycle.cs
> +    protected override QuestPart_Activable_ArchoSpringBuilding Activable_ArchoSpringBuilding => new QuestPart_Activable_ArchoSpringBuilding(Thirst_Flavour_PackDefOf.MSS_SterilizationPlant, 3);
its in the settings no?

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestPartActivable_BuildingUnavailable.cs
> +        bool val = Find.World.GetComponent<ArchospringVictoryWorldComponent>().BuildingAvailable.GetWithFallback(BuildingDef, false);
only do this after your interval, you don't want to be doing this every tick, it's not huge but it's a for loop not a simple lookup so it's just better form. I'd probably also make this less frequent. 60 is very frequent. 1s on speed 1 is a bit much. Alternatively you can add a static cached getter to the component to avoid the loop but that's probably overkill

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestPartActivable_BuildingUnavailable.cs
> +        if (Find.TickManager.TicksGame % 60 != 0 || val)
be a bit careful with this, I don't think quests necessarily tick every tick so you might miss the 60. Better to check less often but keep an int of "nextCheck" tick and if TicksGame < nextCheck then skip.

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestPart_Activable_ArchoSpringBuilding.cs
> +        if (Find.TickManager.TicksGame % 60 != 0 || Find.World.GetComponent<ArchospringVictoryWorldComponent>().BuildingComponentCount.GetWithFallback(Def, 0) < Count)
as above, maybe a < instead of !=

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestPart_Filter_ArchoComponent.cs
> +        get => Find.World.GetComponent<ArchospringVictoryWorldComponent>().ArchoComponentsSeenByPlayer.Select(t=>(GlobalTargetInfo)t).Take(3);
isn't this a setting

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/Rewards/Reward_ArhcospringBuildingSiteMap.cs
> +        throw new NotImplementedException();
sus

2024-10-06 22:21 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/Rewards/Reward_ArhcospringBuildingSiteMap.cs
> +        throw new NotImplementedException();
sus

2024-10-06 22:21 UTC, feldoh commented on Common/Textures/Things/Building/Special/MSS_Water_CatalyticSeparator.png
no notes; perfection

2024-10-06 22:21 UTC, feldoh commented on Compatibility/sarg.alphapropsparks/Patches/MSS_Thirst_WaterQuest.xml
> +    <!-- <Operation Class="PatchOperationAdd"> -->
cruft?

2024-10-06 22:53 UTC, keyz182 commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/Building_ArchoMachine.cs
> +        Find.World.GetComponent<ArchospringVictoryWorldComponent>().BuildingComponentCount.SetOrAdd(def, innerContainer.Count);
There should only ever be one per Def, otherwise something is very wrong.

2024-10-07 09:22 UTC, keyz182 commented
I've addressed all but the tick comparisons for now. Those comparisons are from the base game. I'll try to make them more robust, but will do so when I have time to more thoroughly test.

2024-10-07 16:36 UTC, feldoh approved these changes

2024-10-07 16:36 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_BecomeNeutral.cs
> +        QuestPart_Activalble_FactionRelations questCompleteActivable = new QuestPart_Activalble_FactionRelations(targetFaction, asker.Faction, targetRelationKind);
Just a spelling nitpick `QuestPart_Activalble_FactionRelations`
should probably be 
`QuestPart_Activatable_FactionRelations` or `QuestPart_Activable_FactionRelations`

2024-10-07 16:36 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestPartActivable_BuildingUnavailable.cs
> +        Scribe_Values.Look(ref NextCheck, "NextCheck");
this is fine but pro tip you don't need to save it. If you're setting `NextCheck = Find.TickManager.TicksGame + 600` then it'll init to 0 so check once at start up then sync itself. This is totally fine so not worth fixing but imo it's a tidier model just because the actual exact tick really doesn't matter

2024-10-07 16:36 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestPart_Activalble_FactionRelations.cs
> +        if(TargetFaction.PlayerRelationKind == RelationKind)
Should this be a better than relationship. i.e. if someone has target neutral but jumps to ally, skipping friends by dumping a load of yayo on them or something I think they'd not complete the quest and they'd have to go and raid them to bring it back down XD

2024-10-07 18:29 UTC, keyz182 commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_BecomeNeutral.cs
> +        QuestPart_Activalble_FactionRelations questCompleteActivable = new QuestPart_Activalble_FactionRelations(targetFaction, asker.Faction, targetRelationKind);
Probably should, but the in-game classes (and the parent class) are `Activable` so stuck with it for consistency

2024-10-07 18:43 UTC, keyz182 commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestPartActivable_BuildingUnavailable.cs
> +        Scribe_Values.Look(ref NextCheck, "NextCheck");
Yeah, I think I got the relationship reversed between the two numbers in my head 🤦

2024-10-07 18:44 UTC, keyz182 commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestPart_Activalble_FactionRelations.cs
> +        if(TargetFaction.PlayerRelationKind == RelationKind)
Yup

2024-10-07 23:41 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestNode_Root_BecomeNeutral.cs
> +        QuestPart_Activalble_FactionRelations questCompleteActivable = new QuestPart_Activalble_FactionRelations(targetFaction, asker.Faction, targetRelationKind);
Activable not Activalble
you've got a stray `L`

2024-10-09 21:30 UTC, feldoh commented on 1.5/Patches/MSS_Thirst_Archospring.xml
> +            <reportString>activating archospring.</reportString>
should really be a translation :p

2024-10-09 21:30 UTC, feldoh commented on 1.5/Patches/MSS_Thirst_Archospring.xml
> +        <xpath>Defs/WorldObjectDef[defName="Site"]/comps</xpath>
that doesn't seem right? Won't this add it to ALL sites?

2024-10-09 21:30 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/Building_ArchoMachine.cs
> +        return innerContainer.Count >= 3;
shouldn't this be using the ArchotechComponentsToCompleteBuilding setting

2024-10-09 21:30 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/MapGen/SymbolResolver_Archospring.cs
> +      // // Add sleeping mechs
cruft

2024-10-09 21:30 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestPart_Activable_ArchoSpringBuilding.cs
> -        Scribe_Values.Look(ref NextCheck, "NextCheck");
dropping this is correct but the NextCheck should be `NextCheck = Find.TickManager.TicksGame + 600;` not `NextCheck += 600;` because otherwise post load it'll run like a thousand times to catch up.

2024-10-09 21:30 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestPart_Activable_FactionRelations.cs
> +        NextCheck += 300;
```suggestion
        NextCheck = Find.TickManager.TicksGame + 300;
```

2024-10-09 21:30 UTC, feldoh commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestPart_SubquestGenerator_ArchoHunt.cs
> +        get => Find.World.GetComponent<ArchospringVictoryWorldComponent>().ArchoComponentsSeenByPlayer.Where(t=>t.ParentHolder is not Building_ArchoMachine).Select(t=>(GlobalTargetInfo)t).Take(3);
shouldn't this use the setting

2024-10-09 21:34 UTC, keyz182 commented on 1.5/Patches/MSS_Thirst_Archospring.xml
> +            <reportString>activating archospring.</reportString>
Copied from in-game. Not sure it's actually used. Will look to see if it is, and how, and if it's being translated.

2024-10-09 21:35 UTC, keyz182 commented on 1.5/Patches/MSS_Thirst_Archospring.xml
> +        <xpath>Defs/WorldObjectDef[defName="Site"]/comps</xpath>
That's how the other Comp for doing detection of all enemies dead is set up. Will see if there's a more targeted way I can do it. Maybe when I create the site, I can add the comp in code?

2024-10-09 21:35 UTC, keyz182 commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/Building_ArchoMachine.cs
> +        return innerContainer.Count >= 3;
Yes

2024-10-09 21:37 UTC, keyz182 commented on 1.5/Source/Thirst_Flavour_Pack/VictoryQuest/QuestPart_SubquestGenerator_ArchoHunt.cs
> +        get => Find.World.GetComponent<ArchospringVictoryWorldComponent>().ArchoComponentsSeenByPlayer.Where(t=>t.ParentHolder is not Building_ArchoMachine).Select(t=>(GlobalTargetInfo)t).Take(3);
This is just picking a few to show in the UI on the quest page as hyperlinks. I picked 3 as it "looked" the cleanest. More made the quest page crowded. But I can point it to the setting anyway.

2024-10-09 23:29 UTC, keyz182 commented on 1.5/Patches/MSS_Thirst_Archospring.xml
> +            <reportString>activating archospring.</reportString>
looks like none of the reportstrings in-game are transalated that I can see, so leaving for now

2024-10-09 23:29 UTC, keyz182 commented on 1.5/Patches/MSS_Thirst_Archospring.xml
> +        <xpath>Defs/WorldObjectDef[defName="Site"]/comps</xpath>
Wasn't behaving adding it directly, so instead I've just dropped the check interval to every 5 seconds so it's low impact.

2024-10-10 00:14 UTC, feldoh commented on 1.5/Patches/MSS_Thirst_Archospring.xml
> +        <xpath>Defs/WorldObjectDef[defName="Site"]/comps</xpath>
There's some comp setup shenanigans possibly, what a pity. I wonder if a sitePart would be able to isolate it better 🤷 ah well. bloody weird that the site maker hard codes that one world object type isn't it :(

2024-10-10 00:15 UTC, feldoh approved these changes

2024-10-11 20:44 UTC, merged

2024-10-11 20:44 UTC, MrSamuelStreamer commented
Initial merge, will retest